### ISSUE TITLE
vMix Crash

### ISSUE THREAD

**Issue by stevespaw** [nrkno/sofie-sisyfos-audio-controller#11]
I am trying to tun Sisyfos standalone with vMix version 26 (now 27). I created a simple project with just 4 camera inputs.
Using Docker container with:

docker pull ghcr.io/nrkno/sofie-sisyfos-audio-controller:master
docker volume create sisyfos-vol
sudo docker run --mount source=sisyfos-vol,target=/opt/sisyfos-audio-controller/storage --network="host" ghcr.io/nrkno/sofie-sisyfos-audio-controller:master

Container starts just fine and the Web GUI is available. vMix is available as an option. This is without vMix currently running.
<img width="508" alt="image" src="https://github.com/nrkno/sofie-sisyfos-audio-controller/assets/11045430/dbd89b33-c1ca-41c5-ae48-e249620e5ae9">

When I launch vMix, it crashes almost instantly with this:

/opt/sisyfos-audio-controller/server/dist/server/src/utils/mixerConnections/VMixMixerConnection.js:125
                const { inputGain, muteOn, pflOn, pgmOn, voOn } = store_1.state.faders[0].fader[assignedFader];
                        ^
TypeError: Cannot destructure property 'inputGain' of 'store_1.state.faders[0].fader[assignedFader]' as it is undefined.
    at /opt/sisyfos-audio-controller/server/dist/server/src/utils/mixerConnections/VMixMixerConnection.js:125:25
    at Array.forEach (<anonymous>)
    at /opt/sisyfos-audio-controller/server/dist/server/src/utils/mixerConnections/VMixMixerConnection.js:113:26
    at /opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:291:21
    at Array.forEach (<anonymous>)
    at ConnectionTCP.emitXmlMessage (/opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:290:27)
    at ConnectionTCP._processBufferXMLmessage (/opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:584:14)
    at ConnectionTCP._processBuffer (/opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:206:29)
    at ConnectionTCP._processBufferNonXMLmessage (/opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:545:14)
    at ConnectionTCP._processBuffer (/opt/sisyfos-audio-controller/node_modules/node-vmix/dist/modules/connection-tcp.js:209:25)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

**Comment by stevespaw** [comment]
UPDATE! I did not think that I could go into the channel routing without it running. 
Without vMix running, I went into the channel routing and did the 1:1.
<img width="305" alt="image" src="https://github.com/nrkno/sofie-sisyfos-audio-controller/assets/11045430/b515960a-3434-4247-9292-016140136efe">

Restarted Sisyfos and then vMix.
Success - No crash and it is connected.

Now I can start to play with this. I will have a few questions I am sure.
Thanks.

**Comment by stevespaw** [comment]
It seems that any fader routing besides 1:1 will crash Sisyfos.

**Comment by olzzon** [comment]
As i wrote in the same issue you have opened in TV2/Sisyfos, you can add this:
```
  if (!state.faders[0].fader[assignedFaderIndex]) {
                    return
                }
```

FROM TV2 ISSUE #285
@stevespaw It's related to the doesChannelExists, it looks like it is taken for given that all channels in Sisyfos has a fader assigned to it.
So maybe a workaround that could work would be to assign all vMix channels to a fader (route 1:1)
But as i don't have acces to a vMix i can't test this.

To fix the issue in the code either "this.doesChannelExists" check should be enhanced to also check whether it's assigned to a fader, or a second check "if (!state.faders[0].fader[assignedFaderIndex])" should be added like in this example:
```
                if (!this.doesChannelExists(input.number - 1)) {
                    return
                }

                const { outputLevel, fadeActive } =
                    state.channels[0].chMixerConnection[this.mixerIndex]
                        .channel[input.number - 1]
                const assignedFaderIndex = this.getAssignedFaderIndex(input.number - 1)
                if (!state.faders[0].fader[assignedFaderIndex]) {
                    return
                }
                const { inputGain, muteOn, pflOn, pgmOn, voOn } =
                    state.faders[0].fader[assignedFaderIndex]
    ```
